### ISSUE TITLE
Uncaught Error: Class 'ICal\ICal' 

### ISSUE THREAD

**Issue by uhlhosting** [pulsejet/banner-ics#9]
```
[root@cp logs]# tail -f errors.log 
[15-Oct-2022 21:31:05 Europe/Prague] PHP Fatal error:  Uncaught Error: Class 'ICal\ICal' not found in /var/www/html/roundcube/plugins/banner_ics/banner_ics.php:60
Stack trace:
#0 /var/www/html/roundcube/plugins/banner_ics/banner_ics.php(43): banner_ics->process_attachment(Array, Object(rcube_message), Object(rcube_message_part))
#1 /var/www/html/roundcube/program/lib/Roundcube/rcube_plugin_api.php(518): banner_ics->ics_banner(Array)
#2 /var/www/html/roundcube/program/actions/mail/show.php(366): rcube_plugin_api->exec_hook('message_objects', Array)
#3 /var/www/html/roundcube/program/include/rcmail_output_html.php(1484): rcmail_action_mail_show::message_objects(Array)
#4 [internal function]: rcmail_output_html->xml_command(Array)
#5 /var/www/html/roundcube/program/include/rcmail_output_html.php(1322): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#6 /var/www/html/roundcube/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml('<roundcube:incl...')
#7 /var/www/html/roundcube/program/include/rcmail_output_html.php(654): in /var/www/html/roundcube/plugins/banner_ics/banner_ics.php on line 60
```

I got this while trying to deploy, running latest stable roundcube 1.6.0 .

**Comment by gotspatel** [comment]
`PHP Fatal error:  Uncaught Error: Class "ical\ical" not found in C:\inetpub\wwwroot\roundcube\plugins\banner_ics\banner_ics.php:60
Stack trace:
#0 C:\inetpub\wwwroot\roundcube\plugins\banner_ics\banner_ics.php(43): banner_ics->process_attachment()
#1 C:\inetpub\wwwroot\roundcube\program\lib\Roundcube\rcube_plugin_api.php(513): banner_ics->ics_banner()
#2 C:\inetpub\wwwroot\roundcube\program\actions\mail\show.php(346): rcube_plugin_api->exec_hook()
#3 C:\inetpub\wwwroot\roundcube\program\include\rcmail_output_html.php(1484): rcmail_action_mail_show::message_objects()
#4 [internal function]: rcmail_output_html->xml_command()
#5 C:\inetpub\wwwroot\roundcube\program\include\rcmail_output_html.php(1322): preg_replace_callback()
#6 C:\inetpub\wwwroot\roundcube\program\include\rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#7 C:\inetpub\wwwroot\roundcube\program\include\rcmail_output_html.php(654): rcmail_output_html->parse()
#8 C:\inetpub\wwwroot\roundcube\program\actions\mail\show.php(164): rcmail_output_html->send()
#9 C:\inetpub\wwwroot\roundcube\program\include\rcmail.php(275): rcmail_action_mail_show->run()
#10 C:\inetpub\wwwroot\roundcube\index.php(286): rcmail->action_handler()
#11 C:\inetpub\wwwroot\roundcube\public_html\index.php(26): include('...')
#12 {main}
  thrown in C:\inetpub\wwwroot\roundcube\plugins\banner_ics\banner_ics.php on line 60
`


Roundcube stable 1.5.2 got this error. any suggestions please

There are two ics in the mail attached Part1.3.ics and invice.ics

**Comment by pulsejet** [comment]
How did you install the plugin? You need to do composer require for it to get the deps.

**Comment by gotspatel** [comment]
Php composer.phar require radialapps/banner-ics


And it had installed on ics parser also but still i got this error

roundcube 1.5.2 on iis with php 8.0 win server 2019

**Comment by pulsejet** [comment]
Can you try doing `composer install` in the plugin directory?

> roundcube 1.5.2 on iis with php 8.0 win server 2019

This could be the issue. Never tested on win.

**Comment by gotspatel** [comment]
Can you please advise the dependencies 
I will try manually installing them

`Can you try doing composer install in the plugin directory? `

tried already

**Comment by pulsejet** [comment]
https://github.com/pulsejet/banner-ics/blob/master/composer.json

**Comment by gotspatel** [comment]
johngrogg/ics-parser

This is already installed with this package by composer

Anything else to configure?

**Comment by pulsejet** [comment]
Nope. You want to debug why it can't find the class ICal on line 60. Autoloading issue?

**Comment by gotspatel** [comment]
Yes will try to make it work

**Comment by gotspatel** [comment]
Sorry I giveup I tried many things but unable to make it work (don't have much knowledge about php or RC plugins) but I am sure there is some compatibility issue.

johngrogg/ics-parser being install is version 2.2.2 which is the last stable in ver 2

I will monitor this and request for any further info to debug and make this beautiful plugin work.
Regards

**Comment by ulab** [comment]
Since I had problems with the composer installation, I just manually put the `Event.php`and `ICal.php` in a new include folder and modified `banner_ics.php` to include them.
